### ISSUE TITLE
字体在部分软件中出现异常

### ISSUE THREAD

**Issue by headless-knight** [Leroy-X/Hack-Sara#1]
我使用了一下Hack-Sara这个字体，在部分软件中会出现异常，比如在Notepad2中设置该字体会不生效，会显示为默认字体。而在JetBrains的IDE如IDEA、CLion中中文部分无法显示。
设置为FiraCode时：
[![WYQIFs.png](https://z3.ax1x.com/2021/07/19/WYQIFs.png)](https://imgtu.com/i/WYQIFs)
设置为骇客黑体时：
[![WYQjw4.png](https://z3.ax1x.com/2021/07/19/WYQjw4.png)](https://imgtu.com/i/WYQjw4)

**Comment by Leroy-X** [comment]
感谢你的反馈，
Notepad2中我这边测试可以正常显示；
JetBrinas的IDE我在字体设置选择列表中找不到字体，原因未知

**Comment by headless-knight** [comment]
@Leroy-X 
我再次测试了一下，我使用的Notepad2是Zufuliu维护的版本`https://github.com/zufuliu/notepad2`，当我字体渲染选择为Direct2D时，该字体会变为默认字体。
[![WYbKwn.png](https://z3.ax1x.com/2021/07/20/WYbKwn.png)](https://imgtu.com/i/WYbKwn)
当设置为传统GDI时能正常显示
[![WYbawR.png](https://z3.ax1x.com/2021/07/20/WYbawR.png)](https://imgtu.com/i/WYbawR)

所以Jetbrains下的情况可能也与字体渲染技术有关

同时字体中文名称似乎不可用，不知是有意为之，还是BUG，在VSCode下设置为骇客黑体不生效。
[![WYLrse.png](https://z3.ax1x.com/2021/07/20/WYLrse.png)](https://imgtu.com/i/WYLrse)
设置为Hack Sara方可生效，在Notepad2与JetbrainsIDE中也均为Hack Sara。
[![WYLbon.png](https://z3.ax1x.com/2021/07/20/WYLbon.png)](https://imgtu.com/i/WYLbon)

**Comment by Leroy-X** [comment]
感谢反馈，Notepad2的渲染方式确实对字体有影响，传统模式下可以正常显示；
字体安装时，选择所有用户，JetBrains的IDE如IDEA可以正常显示，我是默认设置，暂不知哪里修改字体渲染方式；
是的，部分软件识别不到中文名(photoshop中文名识别已修复，其他软件我不知道他是如何识别中文名的)，目前的解决方法就是强制修改字体英文名称为中文，但这样可能会降低兼容性；
![01](https://user-images.githubusercontent.com/13515498/126257876-8702b565-e127-4bc2-ae08-d23d0fb75e98.png)

**Comment by Leroy-X** [comment]
@headless-knight 试了多次，Direct 2D渲染的问题依旧解决不了，以后有进展在予以更新

**Comment by Leroy-X** [comment]
@headless-knight 
Direct 2D字体渲染的问题已修复，你可以试下JetBrains可以了吗，我这边JetBrains一直正常；
![01](https://user-images.githubusercontent.com/13515498/126343308-d29b0c50-bb06-4023-999b-d45407c56a1f.png)

**Comment by headless-knight** [comment]
@Leroy-X 
感谢作者的工作，我试了一下，的确在Direct 2D渲染下可用了。至于在JetBrains的软件IDEA等软件中的问题，我再次看了一下，发现似乎和我之前想的不一样，并不是无法显示中文，而是很诡异的注释会消失。

设置为Fira Code
[![WUZafP.png](https://z3.ax1x.com/2021/07/20/WUZafP.png)](https://imgtu.com/i/WUZafP)

设置为Hack Sara
[![WUZywj.png](https://z3.ax1x.com/2021/07/20/WUZywj.png)](https://imgtu.com/i/WUZywj)

**Comment by Leroy-X** [comment]
“执行任务”可以正常显示，似乎是斜体后无法显示

**Comment by Leroy-X** [comment]
JetBrains的临时解决方法，在颜色主体中禁用斜体显示。
参考链接: https://www.cnblogs.com/xiangsui/p/14306672.html
